package sync

import (
	"fmt"
	"strings"

	"github.com/archrail/archrail/internal/model"
)

// GeneratedMarker identifies an Archrail-generated file and warns against manual
// edits.
const GeneratedMarker = "<!-- GENERATED BY ARCHRAIL — DO NOT EDIT. Run `archrail sync` to regenerate. -->"

// ArchrailMD is the canonical adapter: a human- and agent-readable Markdown file.
type ArchrailMD struct{}

func (ArchrailMD) Name() string     { return DefaultAdapter }
func (ArchrailMD) FileName() string { return "ARCHRAIL.md" }

// Render produces deterministic Markdown describing the adopted profile's rules.
func (ArchrailMD) Render(in RenderInput) string {
	var b strings.Builder
	b.WriteString(GeneratedMarker + "\n\n")
	b.WriteString("# Architecture Standards (Archrail)\n\n")
	fmt.Fprintf(&b, "**Profile:** `%s`  \n", in.ProfileName)
	fmt.Fprintf(&b, "**Version:** `%s`\n\n", in.ProfileVersion)
	if in.ProfileDescription != "" {
		b.WriteString(in.ProfileDescription + "\n\n")
	}
	b.WriteString("This project must conform to the following architecture rules. ")
	b.WriteString("These constraints are enforced by `archrail check`.\n\n")

	if len(in.Rules) == 0 {
		b.WriteString("_No rules defined._\n")
		return b.String()
	}

	b.WriteString("## Rules\n\n")
	for _, r := range sortedRules(in.Rules) {
		sev := r.Severity
		if sev == model.SeverityUnset {
			sev = "(default)"
		}
		fmt.Fprintf(&b, "### `%s` — %s\n\n", r.ID, r.Type)
		if r.Description != "" {
			fmt.Fprintf(&b, "%s\n\n", r.Description)
		}
		fmt.Fprintf(&b, "- Severity: %s\n", sev)
		if r.Type == "semantic" {
			if a := decodeString(r, "assertion"); a != "" {
				fmt.Fprintf(&b, "- Assertion: %s\n", a)
			}
			if s := decodeString(r, "scope"); s != "" {
				fmt.Fprintf(&b, "- Scope: %s\n", s)
			}
		}
		b.WriteString("\n")
	}
	return b.String()
}
